
name: 'snowflake_db_nba_data'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:        
  - "target"
  - "dbt_packages"
  - "tests"

on-run-start: "INSERT INTO NBA_DB.REPORTS.DBT_AUDITS (audit_type) VALUES ('run_start')"

on-run-end: "INSERT INTO NBA_DB.REPORTS.DBT_AUDITS (audit_type) VALUES ('run_end')"

models:  

  pre-hook: "INSERT INTO NBA_DB.REPORTS.DBT_AUDITS (audit_type) VALUES ('model_start')"
  post-hook: "INSERT INTO NBA_DB.REPORTS.DBT_AUDITS (audit_type) VALUES ('model_end')"

  snowflake_db_nba_data:
    
    staging:
      +materialized: view
  
    marts:
      +materialized: view
