snowflake_db_nba_data:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: my_account.us-east-1  
      user: nathanaelrv0415         
      password: <my_password>     
      role: transformer_role          
      warehouse: compute_wh     
      database: nba_db          
      schema: stats_analysis               
      threads: 4   
