default:
  outputs:
    dev:
      account: mnzavfe-mm97348
      database: NBA_DB
      password: **********Ncr2027!
      role: ACCOUNTADMIN
      schema: REPORTS
      threads: 4
      type: snowflake
      user: *********6858841
      warehouse: COMPUTE_WH
  target: dev
