[snowflake]
account = "MNZAVFE-MM97348"
user = "JANDERSON6858841"
password = "JamesRVandNcr2027!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "NBA_DB"
schema = "REPORTS"

token = "eyJraWQiOiI0MzMzNzY4MDMwNjkxMzM0IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiMjU4MzEyNzA4OjI1ODMxMjcxMiIsImlzcyI6IlNGOjEwMTYiLCJleHAiOjE4MTYzNzg4MDF9.2bzEAwzrrS3RdC_pNqB_izkui1IyyTIaaW6OMDwMWsXWc8P0RmlHKGA4FdiGsVCLWwgIPNdMrPZBY2Eqn94Avw"

