[snowflake]
account = "MNZAVFE-MM97348"
user = "********6858841"
password = "*********2027!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "NBA_DB"
schema = "REPORTS"

token = "eyJraWQiOiI0MzMzNzY4MDMwN......."

