-- All of my chat models in the YAML source are derived by my model views BELOW which give rise to an efficient data cach that runs during the deployed Streamlit App 

USE ACCOUNTADMIN;

CREATE OR REPLACE VIEW NBA_DB.REPORTS.PLAYER_SEASON_STATS AS

SELECT
    p.PLAYER_ID,
    p.FULL_NAME,

    t.TEAM_ID,

    p.TEAM_NAME,

    p.YEAR_SEASON AS SEASON,

    p.POINTS_2025 AS POINTS,
    p.ASSISTS_2025 AS ASSISTS,
    p.TRB_2025 AS REBOUNDS,
    p.STEALS_2025 AS STEALS,
    p.BLOCKS_2025 AS BLOCKS

FROM NBA_DB.REPORTS.FCT_PLAYER_MASTER_STATS p

LEFT JOIN NBA_DB.REPORTS.FCT_TEAM_MASTER_STATS t
    ON p.TEAM_NAME = t.TEAM_NAME
;

CREATE OR REPLACE VIEW NBA_DB.REPORTS.TEAM_SEASON_STATS AS

SELECT
    TEAM_ID,
    TEAM_NAME,
    ABBREVIATION,
    CITY,
    STATE,
    YEAR_FOUNDED,
    ARENA,
    OWNER,
    HEADCOACH,
    YEAR_TM AS SEASON,
    TM_POINTS_2022 AS POINTS,
    TM_ASSISTS_2022 AS ASSISTS,
    TM_STEALS_2022 AS STEALS,
    TM_BLOCKS_2022 AS BLOCKS,
    TM_TRB_2022 AS REBOUNDS,
    TM_WINS_2022 AS WINS,
    TM_FG_PCT_2022 AS FIELD_GOAL_PERCENTAGE,
    TM_PT3_PCT_2022 AS THREE_POINT_PERCENTAGE,
    TM_FT_PCT_2022 AS FREE_THROW_PERCENTAGE
FROM NBA_DB.REPORTS.FCT_TEAM_MASTER_STATS
WHERE YEAR_TM = 2022

UNION ALL

SELECT
    TEAM_ID,
    TEAM_NAME,
    ABBREVIATION,
    CITY,
    STATE,
    YEAR_FOUNDED,
    ARENA,
    OWNER,
    HEADCOACH,
    YEAR_TM AS SEASON,
    TM_POINTS_2023,
    TM_ASSISTS_2023,
    TM_STEALS_2023,
    TM_BLOCKS_2023,
    TM_TRB_2023,
    TM_WINS_2023,
    TM_FG_PCT_2023,
    TM_PT3_PCT_2023,
    TM_FT_PCT_2023
FROM NBA_DB.REPORTS.FCT_TEAM_MASTER_STATS
WHERE YEAR_TM >= 2023

UNION ALL

SELECT
    TEAM_ID,
    TEAM_NAME,
    ABBREVIATION,
    CITY,
    STATE,
    YEAR_FOUNDED,
    ARENA,
    OWNER,
    HEADCOACH,
    YEAR_TM AS SEASON,
    TM_POINTS_2024,
    TM_ASSISTS_2024,
    TM_STEALS_2024,
    TM_BLOCKS_2024,
    TM_TRB_2024,
    TM_WINS_2024,
    TM_FG_PCT_2024,
    TM_PT3_PCT_2024,
    TM_FT_PCT_2024
FROM NBA_DB.REPORTS.FCT_TEAM_MASTER_STATS
WHERE YEAR_TM >= 2024;



CREATE OR REPLACE VIEW NBA_DB.REPORTS.PLAYER_CAREER_STATS AS

SELECT
    PLAYER_ID,
    FULL_NAME,
    FIRSTNAME,
    LASTNAME,
    IS_ACTIVE_PLAYER,
    SCHOOL,
    FROMYEAR,
    DRAFTROUND,
    DRAFTNUMBER,
    BIRTHDATE,
    HEIGHTINCHES,
    BODYWEIGHTLBS,

    TEAMS_PLAYED_FOR,
    SEASONS_PLAYED,
    GAMES_PLAYED,

    CAREER_POINTS,
    CAREER_ASSISTS,
    CAREER_TRB,
    CAREER_DRB,
    CAREER_ORB,
    CAREER_BLOCKS,
    CAREER_TURNOVERS,

    CAREER_FG_PCT,
    CAREER_3PT_PCT,
    CAREER_FT_PCT

FROM NBA_DB.REPORTS.INT_PLAYER_CAREER_STATS;
